CREATE TABLE Minions
(
	Id INT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(128) NOT NULL,
	Age TINYINT
)

CREATE TABLE Towns
(
	Id INT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(32) NOT NULL,
)

CREATE TABLE People
(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(200) NOT NULL,
	Picture VARBINARY(2048) NULL,
	Height FLOAT(2) NULL,
	[Weight] FLOAT(2) NULL,
	Gender CHAR(1) NOT NULL CHECK(Gender = 'm' OR Gender = 'f'),
	Birthdate DATETIME2 NOT NULL,
	Biography NVARCHAR(MAX) NULL
)

CREATE TABLE Users
(
	Id BIGINT IDENTITY
		CONSTRAINT PK__Id
		PRIMARY KEY (Id),
	Username VARCHAR(30) NOT NULL
		CONSTRAINT UQ__Username
		UNIQUE (Username),
	[Password] BINARY(64) NOT NULL,
	ProfilePicture VARBINARY(MAX) NULL
		CONSTRAINT CK__ProfilePicture__Max_900KB
		CHECK (DATALENGTH(ProfilePicture) <= 921600),
	LastLoginTime DATETIME2 NULL,
	IsDeleted BIT
		CONSTRAINT DF__IsDeleted__0
		DEFAULT 0
)
